FROM node:16-alpine as build

WORKDIR /app_prod

ENV PATH /app_prod/node_modules/.bin:$PATH

COPY package.json /app_prod/package.json

RUN yarn install --silent
RUN yarn global add react-scripts@4.0.1 --silent

COPY . /app_prod

RUN yarn build

FROM nginx:1.20.0-alpine

COPY --from=build /app_prod/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]