version: '3.8'
services:
  app_development:
    container_name: development-hostgator-frontend-challenge
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
